/*  MOLEKEL, Version 4.3, Date: 11.Nov.02
 *  Copyright (C) 2000-2002 Stefan Portmann (CSCS/ETHZ)
 *  (original IRIX GL implementation, concept and data structure
 *   by Peter F. Fluekiger, CSCS/UNI Geneva)
 *
 *  This software makes use of the 
 *  GLUT http://reality.sgi.com/mjk/glut3/glut3.html
 *  GLUI http://www.cs.unc.edu/~rademach/glui/
 *  libtiff http://www.libtiff.org/tiff-v3.5.5.tar.gz
 *  libjpeg ftp://ftp.uu.net/graphics/jpeg
 *  and in some versions of the 
 *  Mesa http://www.mesa3d.org/
 *  and the 
 *  libimage https://toolbox.sgi.com/toolbox/src/haeberli/libimage/index.html#dl
 *  libraries.
 *  An adapted version of the tr library by Brian Paul
 *  (http://www.mesa3d.org/brianp/TR.html)
 *  is part of the distribution.
 *
 *  The binary code is available free of charge but is not in the
 *  public domain. See license for details on conditions and restrictions.
 *  Source code is only available in the framework of a collaboration. 
 *
 *  Info: http://www.cscs.ch/molekel/
**/


/* interface to the
   original molecular surface program by M.Connolly
*/

#include <GLUT/glut.h>
/*#include <GLUI/glui.h>*/
#include <GL/glui.h>
#include <signal.h>

#include "main.h"
#include "molekel.h"
#include "constant.h"
#include "general.h"
#include "connolly.h"
#include "maininterf.h"
#include "calcdens.h"
#include "connect.h"
#include "glutwin.h"

#ifdef LINUX
#define NOSOCK
#endif

#ifdef WIN32
#define NOSOCK
#endif

float dot_density = 6.0, probe_radius = 1.4, radius_increment = 0;
int   buried_flag = 0, output_flag = 0, vdw;
Conflag conflag = {0, 0, 0};

static char ms_name[120], param_name[120];


#ifdef NOSOCK
void connolly(void)
{
   FILE *fp;
   char *cp, command[150], name[120], str[12];

   if(!actualmol) {
      logprint("load a molecule first");
      update_logs();
      return;
   }

   if(!connolly_params(actualmol)) return;

   green_note("calculating");

#ifdef WIN32
   sprintf(ms_name, "%s\\connolly.ms", "C:\\TEMP");
#else
   sprintf(ms_name, "%s/connolly.ms", starting_directory);
#endif
   if((fp = fopen(ms_name, "w")) == NULL){
      sprintf(str, "Can't create %s", ms_name);
      showinfobox(str);
      return; 
   }
   fclose(fp); /* will be generated by sort */ 

   if((cp = getenv("MOLEKEL")) != NULL){
      strcpy(name, cp);
#ifdef WIN32
      strcat(name, "\\ms");
#else
      strcat(name, "/ms");
#endif
   }
   else {
      /* fprintf(stderr, " Can't find environment variable MOLEKEL\n"); */
      /* yeah, I know : junior-programming... (greetings to MWT) */
#ifdef WIN32
      strcpy(name, starting_directory);
      strcat(name, "\\ms");
#else
      strcpy(name, "/usr/local/lib/molekel/ms");
#endif
   }

#ifdef WIN32
   if(chdir("C:\\TEMP") == -1) {
      fprintf(stderr,"can't change dir to C:\\TEMP directory");
      return;
   }
#else
   if(chdir(starting_directory) == -1) {
      fprintf(stderr,"can't change dir to starting directory");
      return;
   }
#endif

   logprint("");
   logprint("generating connolly surface");
   sprintf(command, "%s", name);
printf("%s\n", command);
   system(command);
//   system("dir");
   to_molcad_format();
   default_read_dots();
   glutSetWindow(mainwin);
   glutPostRedisplay();
}
#else
void connolly(void)
{
   FILE *fp;
   char *cp, command[150], name[120], str[12];
   int child_id, pipeline[2];
   static char *ok_string  = "Dot surface generation terminated\0",
               *err_string = "Error termination of Connolly\0";

   if(!actualmol) {
      logprint("load a molecule first");
      update_logs();
      return;
   }

   if(!connolly_params(actualmol)) return;

   green_note("calculating");

   sprintf(ms_name, "%s/connolly.ms", starting_directory);
   if((fp = fopen(ms_name, "w")) == NULL){
      sprintf(str, "Can't create %s", ms_name);
      showinfobox(str);
      return; 
   }
   fclose(fp); /* will be generated by sort */ 

   if((cp = getenv("MOLEKEL")) != NULL){
      strcpy(name, cp);
   }
   else {
      /* fprintf(stderr, " Can't find environment variable MOLEKEL\n"); */
      /* yeah, I know : junior-programming... (greetings to MWT) */
      strcpy(name, "/usr/local/lib/molekel");
   }
   strcat(name, "/ms");

   child_action_key = CONNOLLY;

   if(chdir(starting_directory) == -1) {
      fprintf(stderr,"can't change dir to starting directory");
      return;
   }

   if(!pipein){
      if(pipe(pipeline) < 0){
         perror("opening communication pipe...");
         return;
      }
      pipein = pipeline[0];
      pipeout = pipeline[1];
   }
   
   if((child_id = fork()) == -1){
      fprintf(stderr, "can't create child...\n");
      return;
   }

   if(child_id){                   /* parent */
      if(!did_sigset){
         sigset(SIGCLD, sighandler);
         did_sigset = 1;
      }
   }
   else {                          /* child */
      close(pipein);
      sprintf(command, "nice -%d %s", 19, name);
      printf("%s\n", command);
      if(system(command)) {
         if(write(pipeout, err_string, strlen(err_string) + 1) < 0)
            perror("writing message...");
      }
      else {
         to_molcad_format();
         if(write(pipeout, ok_string, strlen(ok_string) + 1) < 0)
            perror("writing message...");
      }
      close(pipeout);
      exit(0);
   }
}
#endif


int connolly_params(Mol *mp)
{
   FILE *fp;
   int  atomtype[30];
   int  numtypes, newtype;
   register int i;
   AtoM *ap;
   char str[200];

#ifdef WIN32
   sprintf(param_name, "%s\\fort.1", "C:\\TEMP");
#else
   sprintf(param_name, "%s/fort.1", starting_directory);
#endif
   if((fp = fopen(param_name, "w")) == NULL){
      sprintf(str, "Can't create %s", param_name);
      showinfobox(str);
      return 0;
   }

   for(ap=mp->firstatom, numtypes=0; ap; ap=ap->next){
      if(!ap->ord) continue; /* dummy-atoms ! */
      for(i=0, newtype=1; i<numtypes; i++){
         if(ap->ord == atomtype[i]){
            newtype = 0;
            break;
         }
      }
      if(newtype) atomtype[numtypes++] = ap->ord;
   }

   buried_flag = conflag.bury;
   output_flag = conflag.bin;
   if(!conflag.lon) output_flag |= 2;
   vdw = probe_radius ? 0 : 1;

   fprintf(fp, "%10.5f%10.5f%5d%5d%5d\n", dot_density, probe_radius,
      buried_flag, output_flag, numtypes);

   for(i=0; i<numtypes; i++){
      fprintf(fp, "%5d%10.5f\n",
         atomtype[i], element[atomtype[i]].rvdw + radius_increment);
   }

   for(ap=mp->firstatom; ap; ap=ap->next){
      fprintf(fp, "%10.5f%10.5f%10.5f%5d%5d%5d\n",ap->coord[0], ap->coord[1],
         ap->coord[2], ap->ord, 2, 1);
   }

   fclose(fp);

   return 1;
}



int to_molcad_format(void)
{
   FILE  *in, *out;
   char  line[120], *cp;
   static char sc[] = "SC", sr[] = "SR";
   float x, y, z, nx, ny, nz, area;
   int   n1, n2, n3, flag, nitem, bury;

   if((in = fopen("SURFACE", "r")) == NULL){
      fprintf(stderr, "Can't open SURFACE for reading\n");
      return 0;
   }
#ifdef WIN32
   if((out = fopen(ms_name, "w")) == NULL){
#else
   if((out = fopen("SURFACE1", "w")) == NULL){
#endif
      fprintf(stderr, "Can't open SURFACE1 for writing\n");
      fclose(in);
      return 0;
   }

   while(fgets(line, 119, in)){
      nitem = sscanf(line, "%d%d%d%d%f%f%f%f%f%f%f%d", &n1, &n2, &n3, &flag,
         &x, &y, &z, &area, &nx, &ny, &nz, &bury);
      cp = (flag == 1) ? sc : sr;
      fprintf(out, "pff%5d   H%9.3f%9.3f%9.3f%3s", n1, x, y, z, cp);
      if(nitem < 12) fprintf(out, "\n");
      else           fprintf(out, "%7.3f%7.3f%7.3f%7.3f\n", area, nx, ny, nz);
   } 
   fclose(in);
   fclose(out);

#ifndef WIN32
   sprintf(line, "sort +1n +6 SURFACE1 > %s", ms_name);
//   sprintf(line, "cat SURFACE1 > %s", ms_name); /* seems to work also without sort */
                                                  /* but file format is sorted! */
#endif

   unlink("SURFACE");
   unlink(param_name);
#ifndef WIN32
   system(line);
   unlink("SURFACE1");
#endif

   return 1;
}

void default_read_dots(void)
{
   read_dots(ms_name);
}
